spring.datasource.url=jdbc:mysql://yLENJjCfYYVmohFNArPnbfijETTURsVA@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=yLENJjCfYYVmohFNArPnbfijETTURsVA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
